// ---------------------------------------------------------------------------
// Shared sample product data used by both collection pages and PDPs.
// Replace with BigCommerce API calls when the store catalog is populated.
// ---------------------------------------------------------------------------

export interface SampleProduct {
  entityId: number;
  name: string;
  path: string;
  plainTextDescription: string;
  description: string; // HTML for PDP
  defaultImage: { url: string; altText: string };
  images: Array<{ url: string; altText: string; isDefault: boolean }>;
  prices: {
    price: { value: number; currencyCode: string };
    salePrice: { value: number; currencyCode: string } | null;
    bulkPricing: Array<{ minimumQuantity: number; maximumQuantity: number }> | null;
  };
  brand: { name: string };
  category: string; // slug of the parent category
  reviewSummary: { summationOfRatings: number; numberOfReviews: number };
  customFields: Array<{ name: string; value: string }>;
}

export const CATEGORIES: Record<string, { name: string; description: string }> = {
  easels: {
    name: "Easels",
    description: "From compact tabletop easels to heavy-duty H-frames, find the perfect support for your work.",
  },
  "brushes-tools": {
    name: "Brushes & Tools",
    description: "Professional-grade brushes, palette knives, and essential tools for every medium.",
  },
  "paints-mediums": {
    name: "Paints & Mediums",
    description: "Artist-quality oils, acrylics, watercolors, and specialty mediums.",
  },
  "canvas-surfaces": {
    name: "Canvas & Surfaces",
    description: "Premium stretched canvases, wood panels, and specialty papers for every technique.",
  },
  "studio-furniture": {
    name: "Studio Furniture",
    description: "Taborets, storage solutions, and furniture designed for the working artist.",
  },
  "gift-sets": {
    name: "Gift Sets",
    description: "Curated sets for the aspiring artist or the seasoned professional.",
  },
};

// Helper: build a single-image gallery from the default image
function singleGallery(img: { url: string; altText: string }) {
  return [{ url: img.url, altText: img.altText, isDefault: true }];
}

// ---------------------------------------------------------------------------
// ALL PRODUCTS — keyed by category slug
// ---------------------------------------------------------------------------

const ALL_PRODUCTS: SampleProduct[] = [
  // ===== EASELS =====
  { entityId: 101, name: "Chevalet Grand H-Frame Studio Easel", path: "/products/chevalet-grand-h-frame", category: "easels", plainTextDescription: "Our flagship heavy-duty H-frame built from kiln-dried European beechwood. Center-tilting mast adjusts from vertical to near-horizontal. Holds canvases up to 78 inches with rock-solid stability.", description: "<p>The Chevalet Grand H-Frame is the easel serious studio artists build their practice around. Crafted from kiln-dried European beechwood and finished with hand-rubbed tung oil, every joint is precision-mortised for decades of rigid, wobble-free service.</p><p>The center-tilting mast provides infinite adjustment from full vertical to near-horizontal, making it equally suited to oils, acrylics, and watercolor. A ratcheting canvas clamp grips stretcher bars securely without marring the wood.</p><p>Heavy-duty locking casters let you reposition the easel effortlessly, then lock it in place for the most vigorous brushwork. A generous lower shelf keeps mediums, brushes, and rags within arm's reach.</p>", defaultImage: { url: "/images/products/chevalet-grand-h-frame.png", altText: "Chevalet Grand H-Frame studio easel holding canvases in a warm-lit artist studio" }, images: [{ url: "/images/products/chevalet-grand-h-frame.png", altText: "Chevalet Grand H-Frame studio easel holding canvases in a warm-lit artist studio", isDefault: true }], prices: { price: { value: 489.99, currencyCode: "USD" }, salePrice: null, bulkPricing: [{ minimumQuantity: 3, maximumQuantity: 9 }] }, brand: { name: "Chevalet" }, reviewSummary: { summationOfRatings: 23, numberOfReviews: 5 }, customFields: [{ name: "Material", value: "Kiln-Dried European Beechwood" }, { name: "Finish", value: "Hand-Rubbed Tung Oil" }, { name: "Max Canvas Height", value: '78"' }, { name: "Weight", value: "38 lbs" }, { name: "Dimensions", value: '25"W x 27"D x 96"H' }] },

  { entityId: 102, name: "Artisan & Co Plein Air French Box Easel", path: "/products/artisan-plein-air-french-box", category: "easels", plainTextDescription: "Classic French box easel with built-in palette, canvas carrier, and divided supply drawer. Folds into a compact carrying case with leather shoulder strap for outdoor painting sessions.", description: "<p>Take your studio outdoors with the Artisan & Co French Box Easel. This all-in-one plein air solution unfolds into a sturdy A-frame easel while keeping your brushes, tubes, and mediums organized in a felt-lined divided drawer.</p><p>The integrated wooden palette slides out for mixing, and the adjustable canvas holder accommodates works up to 34 inches tall. When the session is over, everything folds back into a slim case with a padded leather shoulder strap.</p>", defaultImage: { url: "/images/products/artisan-plein-air-french-box.png", altText: "Artisan and Co French box easel set up outdoors with painting supplies" }, images: [{ url: "/images/products/artisan-plein-air-french-box.png", altText: "Artisan and Co French box easel set up outdoors with painting supplies", isDefault: true }], prices: { price: { value: 279.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Artisan & Co" }, reviewSummary: { summationOfRatings: 17, numberOfReviews: 4 }, customFields: [{ name: "Material", value: "Oiled Beechwood" }, { name: "Max Canvas Height", value: '34"' }, { name: "Folded Size", value: '18"W x 14"D x 6"H' }, { name: "Weight", value: "14 lbs" }, { name: "Includes", value: "Palette, Shoulder Strap, Drawer Dividers" }] },

  { entityId: 103, name: "StudioCraft Compact Tabletop Easel", path: "/products/studiocraft-compact-tabletop", category: "easels", plainTextDescription: "Elegant solid-walnut tabletop easel for display or small-format painting. Adjustable canvas holder with rubber grips. Perfect for apartments, desks, or gallery counters.", description: "<p>The StudioCraft Compact Tabletop Easel proves you don't need a dedicated studio to create. Milled from solid American walnut with a satin lacquer finish, it sits beautifully on any desk, counter, or shelf.</p><p>Rubber-padded canvas grips hold boards and stretched canvases up to 16 inches without slipping. The three-position back leg lets you choose your preferred painting angle.</p>", defaultImage: { url: "/images/products/studiocraft-compact-tabletop.png", altText: "StudioCraft compact tabletop easel in warm walnut finish on a desk" }, images: [{ url: "/images/products/studiocraft-compact-tabletop.png", altText: "StudioCraft compact tabletop easel in warm walnut finish on a desk", isDefault: true }], prices: { price: { value: 79.99, currencyCode: "USD" }, salePrice: { value: 59.99, currencyCode: "USD" }, bulkPricing: null }, brand: { name: "StudioCraft" }, reviewSummary: { summationOfRatings: 36, numberOfReviews: 8 }, customFields: [{ name: "Material", value: "Solid American Walnut" }, { name: "Max Canvas Height", value: '16"' }, { name: "Weight", value: "3 lbs" }, { name: "Dimensions", value: '11"W x 9"D x 16"H' }] },

  { entityId: 104, name: "Oakmont Professional A-Frame Easel", path: "/products/oakmont-professional-a-frame", category: "easels", plainTextDescription: "Workhorse A-frame easel in oiled white oak. Spring-loaded canvas clamp and infinite-adjust mast let you work on pieces from 8 to 50 inches without fumbling with wing nuts.", description: "<p>The Oakmont A-Frame is the no-nonsense studio workhorse. Its clean A-frame geometry keeps your floor space minimal while a spring-loaded canvas clamp grips your work instantly—no wing nuts to fiddle with.</p><p>The telescoping mast locks at any height with a single lever, accepting canvases from 8 to 50 inches. Oiled white oak resists paint drips and cleans easily with a damp cloth.</p>", defaultImage: { url: "/images/products/oakmont-professional-a-frame.png", altText: "Oakmont A-frame easel standing in a sunlit park setting" }, images: [{ url: "/images/products/oakmont-professional-a-frame.png", altText: "Oakmont A-frame easel standing in a sunlit park setting", isDefault: true }], prices: { price: { value: 329.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Oakmont" }, reviewSummary: { summationOfRatings: 14, numberOfReviews: 3 }, customFields: [{ name: "Material", value: "Oiled White Oak" }, { name: "Max Canvas Height", value: '50"' }, { name: "Weight", value: "22 lbs" }, { name: "Dimensions", value: '22"W x 24"D x 72"H' }] },

  { entityId: 105, name: "Chevalet Convertible Studio Easel", path: "/products/chevalet-convertible-studio", category: "easels", plainTextDescription: "Seamlessly switches between upright easel and flat drafting table position. Ideal for artists who work in both oil and watercolor. Locking casters and built-in supply tray included.", description: "<p>Why choose between an easel and a drafting table? The Chevalet Convertible does both. A dual-pivot mechanism lets you tilt the work surface from full vertical through to completely flat in one smooth motion.</p><p>Oil painters work upright; watercolorists lay it flat; illustrators find their sweet spot in between. Locking casters keep it mobile yet steady, and a built-in aluminum supply tray runs the full width of the frame.</p>", defaultImage: { url: "/images/products/chevalet-convertible-studio.png", altText: "Chevalet convertible easel in upright painting position in artist studio" }, images: [{ url: "/images/products/chevalet-convertible-studio.png", altText: "Chevalet convertible easel in upright painting position in artist studio", isDefault: true }], prices: { price: { value: 399.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Chevalet" }, reviewSummary: { summationOfRatings: 9, numberOfReviews: 2 }, customFields: [{ name: "Material", value: "European Beechwood" }, { name: "Max Canvas Height", value: '60"' }, { name: "Weight", value: "32 lbs" }, { name: "Tilt Range", value: "0° (flat) to 90° (vertical)" }] },

  { entityId: 106, name: "Artisan & Co Portable Field Tripod", path: "/products/artisan-portable-field-tripod", category: "easels", plainTextDescription: "Ultra-light aluminum tripod easel that weighs just 3 lbs. Telescoping legs adjust to standing or seated height. Collapses to 21 inches and fits in the included carry bag.", description: "<p>At just 3 pounds, the Artisan & Co Field Tripod disappears into a backpack and sets up in seconds. Anodized aluminum legs telescope from seated to standing height with flip-lock clasps that hold firm on uneven ground.</p><p>The adjustable canvas holder grips boards and canvases up to 32 inches. A nylon carry bag with a shoulder strap is included.</p>", defaultImage: { url: "/images/products/artisan-portable-field-tripod.png", altText: "Artist painting en plein air on an Artisan and Co portable tripod easel by a river" }, images: [{ url: "/images/products/artisan-portable-field-tripod.png", altText: "Artist painting en plein air on an Artisan and Co portable tripod easel by a river", isDefault: true }], prices: { price: { value: 89.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Artisan & Co" }, reviewSummary: { summationOfRatings: 19, numberOfReviews: 5 }, customFields: [{ name: "Material", value: "Anodized Aluminum" }, { name: "Max Canvas Height", value: '32"' }, { name: "Folded Length", value: '21"' }, { name: "Weight", value: "3 lbs" }] },

  { entityId: 107, name: "StudioCraft Gallery Display Easel", path: "/products/studiocraft-gallery-display", category: "easels", plainTextDescription: "Sleek matte-black steel display easel designed for galleries, open studios, and retail. Adjustable ledge accommodates framed works up to 40 inches. Non-scratch floor pads included.", description: "<p>Present your work—or your clients' work—with the StudioCraft Gallery Display Easel. The clean matte-black powder-coated steel frame disappears behind the art, putting all the focus on the piece.</p><p>An adjustable ledge with felt lining protects frames while holding works up to 40 inches. Non-scratch rubber floor pads keep galleries and hardwood floors pristine.</p>", defaultImage: { url: "/images/products/studiocraft-gallery-display.png", altText: "Row of StudioCraft gallery display easels showcasing framed artwork" }, images: [{ url: "/images/products/studiocraft-gallery-display.png", altText: "Row of StudioCraft gallery display easels showcasing framed artwork", isDefault: true }], prices: { price: { value: 149.99, currencyCode: "USD" }, salePrice: null, bulkPricing: [{ minimumQuantity: 5, maximumQuantity: 9 }] }, brand: { name: "StudioCraft" }, reviewSummary: { summationOfRatings: 28, numberOfReviews: 7 }, customFields: [{ name: "Material", value: "Powder-Coated Steel" }, { name: "Finish", value: "Matte Black" }, { name: "Max Canvas Height", value: '40"' }, { name: "Weight", value: "8 lbs" }] },

  { entityId: 108, name: "Oakmont Student Studio Easel", path: "/products/oakmont-student-studio", category: "easels", plainTextDescription: "Affordable full-size studio easel for students and emerging artists. Solid pine construction with adjustable height and a generous supply shelf. Ships flat, assembles in 10 minutes.", description: "<p>The Oakmont Student Studio Easel delivers full-size performance at a student-friendly price. Solid pine construction gives it real weight and stability—no wobbling during energetic brushwork.</p><p>An adjustable mast holds canvases up to 44 inches, while a wide lower shelf keeps your supplies organized. Ships flat-packed and assembles in about 10 minutes with the included hardware.</p>", defaultImage: { url: "/images/products/oakmont-student-studio.png", altText: "Oakmont student easel with palette and canvas in a cozy studio corner" }, images: [{ url: "/images/products/oakmont-student-studio.png", altText: "Oakmont student easel with palette and canvas in a cozy studio corner", isDefault: true }], prices: { price: { value: 159.99, currencyCode: "USD" }, salePrice: null, bulkPricing: [{ minimumQuantity: 10, maximumQuantity: 0 }] }, brand: { name: "Oakmont" }, reviewSummary: { summationOfRatings: 32, numberOfReviews: 8 }, customFields: [{ name: "Material", value: "Solid Pine" }, { name: "Max Canvas Height", value: '44"' }, { name: "Weight", value: "18 lbs" }, { name: "Assembly", value: "10 Minutes, Tools Included" }] },

  { entityId: 109, name: "Chevalet Artist's Sketch Box Easel", path: "/products/chevalet-sketch-box", category: "easels", plainTextDescription: "Premium sketch box easel in oiled beechwood with a felt-lined storage compartment for brushes, tubes, and mediums. Adjustable canvas holder and integrated palette make it a self-contained studio on the go.", description: "<p>The Chevalet Sketch Box Easel is a self-contained painting station in a beautiful beechwood case. A felt-lined compartment keeps brushes, tubes, and palette knives organized, while the integrated wooden palette is always at the ready.</p><p>Set it on any table and the adjustable A-frame holds canvases up to 20 inches. When the session ends, everything tucks away and the brass latch clicks shut.</p>", defaultImage: { url: "/images/products/chevalet-sketch-box.png", altText: "Chevalet sketch box easel holding a vibrant still-life painting in progress" }, images: [{ url: "/images/products/chevalet-sketch-box.png", altText: "Chevalet sketch box easel holding a vibrant still-life painting in progress", isDefault: true }], prices: { price: { value: 219.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Chevalet" }, reviewSummary: { summationOfRatings: 13, numberOfReviews: 3 }, customFields: [{ name: "Material", value: "Oiled Beechwood" }, { name: "Max Canvas Height", value: '20"' }, { name: "Weight", value: "9 lbs" }, { name: "Includes", value: "Palette, Felt-Lined Compartment, Brass Latch" }] },

  // ===== BRUSHES & TOOLS =====
  { entityId: 201, name: "Atelier Pro Studio Brush Set (16pc)", path: "/products/atelier-pro-studio-brush-set", category: "brushes-tools", plainTextDescription: "Our flagship 16-piece studio set with hand-selected natural and synthetic filaments. Includes rounds, flats, filberts, and a fan brush in a walnut roll case.", description: "<p>Sixteen hand-selected brushes covering every stroke you need. The Atelier Pro set includes rounds, flats, brights, filberts, and a fan brush in both natural hair and durable synthetic filaments.</p><p>Each brush features a seamless nickel ferrule and a balanced birch handle. Comes in a rolled walnut canvas case.</p>", defaultImage: { url: "/images/products/atelier-pro-studio-brush-set.png", altText: "Atelier Pro Studio Brush Set featuring 16 professional brushes in various sizes" }, images: [], prices: { price: { value: 189.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Atelier" }, reviewSummary: { summationOfRatings: 22, numberOfReviews: 5 }, customFields: [{ name: "Pieces", value: "16" }, { name: "Filament", value: "Natural & Synthetic Blend" }, { name: "Handle", value: "Birch" }, { name: "Includes", value: "Walnut Roll Case" }] },

  { entityId: 202, name: "Terra Impasto Palette Knife Set (5pc)", path: "/products/terra-impasto-palette-knife-set", category: "brushes-tools", plainTextDescription: "Forged stainless steel palette knives in 5 essential shapes. Offset handles keep your grip clear of the canvas while you build bold, textured layers.", description: "<p>Five forged stainless steel blades in the shapes impasto painters reach for most. The offset handles keep your knuckles above the surface so you can lay paint on fearlessly.</p>", defaultImage: { url: "/images/products/terra-impasto-palette-knife-set.png", altText: "Terra palette knife applying thick paint to canvas" }, images: [], prices: { price: { value: 44.99, currencyCode: "USD" }, salePrice: { value: 34.99, currencyCode: "USD" }, bulkPricing: null }, brand: { name: "Terra Brushworks" }, reviewSummary: { summationOfRatings: 18, numberOfReviews: 4 }, customFields: [{ name: "Pieces", value: "5" }, { name: "Material", value: "Forged Stainless Steel" }, { name: "Handle", value: "Hardwood, Offset" }] },

  { entityId: 203, name: "Bristle & Bloom Fan Brush Collection", path: "/products/bristle-bloom-fan-brush-collection", category: "brushes-tools", plainTextDescription: "Set of 4 fan brushes in natural hog and soft synthetic hair. Designed for blending skies, creating foliage textures, and feathering edges.", description: "<p>Four fan brushes in graduated sizes, split between natural hog bristle and soft synthetic hair. Use the hog fans for bold texture, the synthetics for feathered blending.</p>", defaultImage: { url: "/images/products/bristle-bloom-fan-brush-collection.png", altText: "Bristle and Bloom fan brushes arranged in a studio jar" }, images: [], prices: { price: { value: 42.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Bristle & Bloom" }, reviewSummary: { summationOfRatings: 9, numberOfReviews: 2 }, customFields: [{ name: "Pieces", value: "4" }, { name: "Filament", value: "Natural Hog & Synthetic" }] },

  { entityId: 204, name: "StudioCraft Watercolor Detail Set", path: "/products/studiocraft-watercolor-detail-set", category: "brushes-tools", plainTextDescription: "Precision-pointed watercolor brushes sized 000 to 8. Synthetic sable holds a needle-sharp point while carrying generous washes of pigment.", description: "<p>Precision-pointed synthetic sable brushes in sizes 000 through 8. Each brush snaps to a needle-sharp point yet carries generous washes of pigment. Short handles for close-in control.</p>", defaultImage: { url: "/images/products/studiocraft-watercolor-detail-set.png", altText: "StudioCraft watercolor brush with paint pots on clean white background" }, images: [], prices: { price: { value: 64.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "StudioCraft" }, reviewSummary: { summationOfRatings: 20, numberOfReviews: 5 }, customFields: [{ name: "Sizes", value: "000, 00, 0, 2, 4, 6, 8" }, { name: "Filament", value: "Synthetic Sable" }] },

  { entityId: 205, name: "Artisan & Co Master Palette Set", path: "/products/artisan-co-master-palette-set", category: "brushes-tools", plainTextDescription: "Traditional artist palette paired with two hand-turned mixing brushes. The solid maple palette is pre-oiled and sealed for easy cleanup.", description: "<p>A hand-shaped solid maple palette paired with two hand-turned mixing brushes. The palette is pre-oiled and sealed so dried paint peels right off.</p>", defaultImage: { url: "/images/products/artisan-co-master-palette-set.png", altText: "Artisan and Co palette with brushes on white background" }, images: [], prices: { price: { value: 59.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Artisan & Co" }, reviewSummary: { summationOfRatings: 14, numberOfReviews: 3 }, customFields: [{ name: "Material", value: "Solid Maple" }, { name: "Includes", value: "2 Mixing Brushes" }] },

  { entityId: 206, name: "Terra Heavy Duty Acrylic Set (12pc)", path: "/products/terra-heavy-duty-acrylic-set", category: "brushes-tools", plainTextDescription: "12 thick-filament brushes engineered for heavy body acrylics. Colorful lacquered handles with stainless ferrules that won't loosen under hard use.", description: "<p>Twelve thick-filament brushes built to push heavy body acrylics around without shedding or splaying. Stainless ferrules crimped to colorful lacquered handles that won't loosen under hard use.</p>", defaultImage: { url: "/images/products/terra-heavy-duty-acrylic-set.png", altText: "Terra acrylic brush set with colorful handles spread across worktable" }, images: [], prices: { price: { value: 54.99, currencyCode: "USD" }, salePrice: null, bulkPricing: [{ minimumQuantity: 10, maximumQuantity: 0 }] }, brand: { name: "Terra Brushworks" }, reviewSummary: { summationOfRatings: 16, numberOfReviews: 4 }, customFields: [{ name: "Pieces", value: "12" }, { name: "Filament", value: "Heavy-Duty Synthetic" }] },

  { entityId: 207, name: "Atelier Watercolor Travel Kit", path: "/products/atelier-watercolor-travel-kit", category: "brushes-tools", plainTextDescription: "Compact plein air set with 3 travel brushes, a folding watercolor palette, and a spiral-bound field sketchbook. Everything fits in the included canvas pouch.", description: "<p>Three travel brushes, a folding watercolor palette, and a 40-page cold-press field sketchbook—all tucked inside a waxed canvas pouch that fits in a coat pocket.</p>", defaultImage: { url: "/images/products/atelier-watercolor-travel-kit.png", altText: "Atelier watercolor travel kit with brushes, palette, and sketchbook on wooden desk" }, images: [], prices: { price: { value: 79.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Atelier" }, reviewSummary: { summationOfRatings: 24, numberOfReviews: 6 }, customFields: [{ name: "Includes", value: "3 Brushes, Palette, Sketchbook, Pouch" }] },

  { entityId: 208, name: "Bristle & Bloom Oil Painters Brush", path: "/products/bristle-bloom-oil-painters-brush", category: "brushes-tools", plainTextDescription: "Handmade Chungking hog bristle flat brush with a brass ferrule and long birch handle. The natural flag tips hold oil paint beautifully for smooth, even strokes.", description: "<p>A single handmade Chungking hog bristle flat brush with a brass ferrule and extra-long birch handle. Natural flag tips hold oil paint for smooth, even strokes across the canvas.</p>", defaultImage: { url: "/images/products/bristle-bloom-oil-painters-brush.png", altText: "Bristle and Bloom oil painting brush next to paint tubes on wooden surface" }, images: [], prices: { price: { value: 28.99, currencyCode: "USD" }, salePrice: null, bulkPricing: [{ minimumQuantity: 5, maximumQuantity: 9 }] }, brand: { name: "Bristle & Bloom" }, reviewSummary: { summationOfRatings: 10, numberOfReviews: 2 }, customFields: [{ name: "Filament", value: "Chungking Hog Bristle" }, { name: "Ferrule", value: "Brass" }, { name: "Handle", value: "Long Birch" }] },

  // ===== PAINTS & MEDIUMS =====
  { entityId: 301, name: "Oil Paint Master Set (12 tubes)", path: "/products/oil-paint-master-set", category: "paints-mediums", plainTextDescription: "Professional-grade oil paints in 12 essential colors. High pigment concentration with buttery consistency.", description: "<p>Professional-grade oil paints in 12 essential colors. High pigment concentration with buttery consistency for confident color mixing.</p>", defaultImage: { url: "/images/products/oil-paint-master-set.png", altText: "Oil Paint Master Set" }, images: [], prices: { price: { value: 189.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Gamblin" }, reviewSummary: { summationOfRatings: 18, numberOfReviews: 4 }, customFields: [{ name: "Colors", value: "12" }, { name: "Tube Size", value: "37ml" }] },
  { entityId: 302, name: "Heavy Body Acrylic Set (8 tubes)", path: "/products/heavy-body-acrylic-set", category: "paints-mediums", plainTextDescription: "Artist-quality heavy body acrylics in 8 vibrant colors. Excellent coverage and color strength.", description: "<p>Artist-quality heavy body acrylics in 8 vibrant colors. Excellent coverage and color strength for studio and outdoor work.</p>", defaultImage: { url: "/images/products/heavy-body-acrylic-set.png", altText: "Heavy Body Acrylic Set" }, images: [], prices: { price: { value: 129.99, currencyCode: "USD" }, salePrice: null, bulkPricing: [{ minimumQuantity: 5, maximumQuantity: 9 }] }, brand: { name: "Golden" }, reviewSummary: { summationOfRatings: 22, numberOfReviews: 5 }, customFields: [{ name: "Colors", value: "8" }, { name: "Tube Size", value: "59ml" }] },
  { entityId: 303, name: "Watercolor Pan Set (24 colors)", path: "/products/watercolor-pan-set", category: "paints-mediums", plainTextDescription: "Professional watercolor half-pans in a metal travel tin. Includes 24 lightfast colors and a mixing palette.", description: "<p>Professional watercolor half-pans in a metal travel tin with 24 lightfast colors and a built-in mixing palette.</p>", defaultImage: { url: "/images/products/watercolor-pan-set.png", altText: "Watercolor Pan Set" }, images: [], prices: { price: { value: 89.99, currencyCode: "USD" }, salePrice: { value: 74.99, currencyCode: "USD" }, bulkPricing: null }, brand: { name: "Winsor & Newton" }, reviewSummary: { summationOfRatings: 27, numberOfReviews: 6 }, customFields: [{ name: "Colors", value: "24 Half-Pans" }] },
  { entityId: 304, name: "Linseed Oil (16oz)", path: "/products/linseed-oil", category: "paints-mediums", plainTextDescription: "Cold-pressed linseed oil for oil painting. Increases gloss and transparency while slowing drying time.", description: "<p>Cold-pressed linseed oil that increases gloss and transparency while gently slowing drying time.</p>", defaultImage: { url: "/images/products/linseed-oil.png", altText: "Cold-Pressed Linseed Oil" }, images: [], prices: { price: { value: 14.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Gamblin" }, reviewSummary: { summationOfRatings: 10, numberOfReviews: 2 }, customFields: [{ name: "Size", value: "16 oz" }] },
  { entityId: 305, name: "Gesso Primer (32oz)", path: "/products/gesso-primer", category: "paints-mediums", plainTextDescription: "Professional acrylic gesso for priming canvases and surfaces. Provides excellent tooth for paint adhesion.", description: "<p>Professional acrylic gesso for priming any surface. Provides excellent tooth for paint adhesion.</p>", defaultImage: { url: "/images/products/gesso-primer.png", altText: "Gesso Primer" }, images: [], prices: { price: { value: 18.99, currencyCode: "USD" }, salePrice: null, bulkPricing: [{ minimumQuantity: 6, maximumQuantity: 0 }] }, brand: { name: "Liquitex" }, reviewSummary: { summationOfRatings: 15, numberOfReviews: 3 }, customFields: [{ name: "Size", value: "32 oz" }] },
  { entityId: 306, name: "Cadmium Yellow Deep (150ml)", path: "/products/cadmium-yellow-deep", category: "paints-mediums", plainTextDescription: "Single tube of cadmium yellow deep oil paint. Rich, opaque warm yellow with excellent lightfastness.", description: "<p>Rich, opaque cadmium yellow deep oil paint with excellent lightfastness.</p>", defaultImage: { url: "/images/products/cadmium-yellow-deep.png", altText: "Cadmium Yellow Deep Oil Paint" }, images: [], prices: { price: { value: 24.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Old Holland" }, reviewSummary: { summationOfRatings: 5, numberOfReviews: 1 }, customFields: [{ name: "Tube Size", value: "150ml" }] },
  { entityId: 307, name: "Acrylic Glazing Medium (8oz)", path: "/products/acrylic-glazing-medium", category: "paints-mediums", plainTextDescription: "Transparent glazing medium for acrylics. Extends working time and creates luminous transparent layers.", description: "<p>Extends acrylic working time and creates luminous transparent layers.</p>", defaultImage: { url: "/images/products/acrylic-glazing-medium.png", altText: "Acrylic Glazing Medium" }, images: [], prices: { price: { value: 16.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Golden" }, reviewSummary: { summationOfRatings: 8, numberOfReviews: 2 }, customFields: [{ name: "Size", value: "8 oz" }] },
  { entityId: 308, name: "Gouache Set (18 tubes)", path: "/products/gouache-set", category: "paints-mediums", plainTextDescription: "Professional gouache paint set in 18 opaque colors. Ideal for illustration, design, and fine art.", description: "<p>18 opaque gouache colors ideal for illustration, design, and fine art.</p>", defaultImage: { url: "/images/products/gouache-set.png", altText: "Gouache Set 18 Colors" }, images: [], prices: { price: { value: 64.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Holbein" }, reviewSummary: { summationOfRatings: 20, numberOfReviews: 5 }, customFields: [{ name: "Colors", value: "18" }] },
  { entityId: 309, name: "Turpenoid Natural (32oz)", path: "/products/turpenoid-natural", category: "paints-mediums", plainTextDescription: "Non-toxic turpentine alternative for oil painting. Low odor, safer for studio environments.", description: "<p>Non-toxic, low-odor turpentine alternative for oil painting. Safer for enclosed studio environments.</p>", defaultImage: { url: "/images/products/turpenoid-natural.png", altText: "Turpenoid Natural Solvent" }, images: [], prices: { price: { value: 19.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Weber" }, reviewSummary: { summationOfRatings: 6, numberOfReviews: 2 }, customFields: [{ name: "Size", value: "32 oz" }] },

  // ===== CANVAS & SURFACES =====
  { entityId: 401, name: "Stretched Canvas 18x24 (6-pack)", path: "/products/stretched-canvas-18x24", category: "canvas-surfaces", plainTextDescription: "Gallery-wrapped stretched canvases, 18x24 inches. Triple-primed cotton duck with kiln-dried stretcher bars.", description: "<p>Gallery-wrapped stretched canvases, 18x24 inches. Triple-primed cotton duck on kiln-dried stretcher bars.</p>", defaultImage: { url: "/images/products/stretched-canvas-18x24.png", altText: "Stretched Canvas 18x24 Pack" }, images: [], prices: { price: { value: 89.99, currencyCode: "USD" }, salePrice: null, bulkPricing: [{ minimumQuantity: 3, maximumQuantity: 9 }] }, brand: { name: "Fredrix" }, reviewSummary: { summationOfRatings: 18, numberOfReviews: 4 }, customFields: [{ name: "Size", value: '18" x 24"' }, { name: "Quantity", value: "6" }] },
  { entityId: 402, name: "Belgian Linen Canvas 24x30", path: "/products/belgian-linen-canvas-24x30", category: "canvas-surfaces", plainTextDescription: "Premium Belgian linen canvas, oil-primed. Museum-quality surface for professional oil painting.", description: "<p>Premium Belgian linen canvas, oil-primed for museum-quality oil painting.</p>", defaultImage: { url: "/images/products/belgian-linen-canvas-24x30.png", altText: "Belgian Linen Canvas" }, images: [], prices: { price: { value: 64.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Claessens" }, reviewSummary: { summationOfRatings: 10, numberOfReviews: 2 }, customFields: [{ name: "Size", value: '24" x 30"' }] },
  { entityId: 403, name: "Birch Wood Panel 12x16", path: "/products/birch-wood-panel-12x16", category: "canvas-surfaces", plainTextDescription: "Smooth birch plywood painting panel with cradled edges. Pre-gessoed and ready for all media.", description: "<p>Smooth birch plywood painting panel with cradled edges. Pre-gessoed and ready for all media.</p>", defaultImage: { url: "/images/products/birch-wood-panel-12x16.png", altText: "Birch Wood Panel" }, images: [], prices: { price: { value: 22.99, currencyCode: "USD" }, salePrice: { value: 18.99, currencyCode: "USD" }, bulkPricing: null }, brand: { name: "Ampersand" }, reviewSummary: { summationOfRatings: 14, numberOfReviews: 3 }, customFields: [{ name: "Size", value: '12" x 16"' }] },
  { entityId: 404, name: "Watercolor Paper Block (140lb)", path: "/products/watercolor-paper-block-140lb", category: "canvas-surfaces", plainTextDescription: "Cold-pressed watercolor paper block, 140lb weight. 20 sheets of archival cotton rag paper.", description: "<p>Cold-pressed cotton rag watercolor paper block. 140lb, 20 sheets, archival quality.</p>", defaultImage: { url: "/images/products/watercolor-paper-block-140lb.png", altText: "Watercolor Paper Block" }, images: [], prices: { price: { value: 34.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Arches" }, reviewSummary: { summationOfRatings: 20, numberOfReviews: 5 }, customFields: [{ name: "Weight", value: "140 lb" }, { name: "Sheets", value: "20" }] },
  { entityId: 405, name: "Canvas Roll (Belgian Linen 6ft)", path: "/products/canvas-roll-belgian-linen", category: "canvas-surfaces", plainTextDescription: "Unprimed Belgian linen canvas roll, 54 inches wide by 6 feet. For custom stretching and large works.", description: "<p>Unprimed Belgian linen canvas roll. 54\" wide by 6 feet for custom stretching.</p>", defaultImage: { url: "/images/products/canvas-roll-belgian-linen.png", altText: "Belgian Linen Canvas Roll" }, images: [], prices: { price: { value: 149.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Claessens" }, reviewSummary: { summationOfRatings: 9, numberOfReviews: 2 }, customFields: [{ name: "Width", value: '54"' }, { name: "Length", value: "6 ft" }] },
  { entityId: 406, name: "Mixed Media Pad 11x14", path: "/products/mixed-media-pad-11x14", category: "canvas-surfaces", plainTextDescription: "Heavyweight mixed media paper pad, 184lb. Works with watercolor, acrylic, gouache, and ink.", description: "<p>Heavyweight 184lb mixed media paper pad for watercolor, acrylic, gouache, and ink.</p>", defaultImage: { url: "/images/products/mixed-media-pad-11x14.png", altText: "Mixed Media Paper Pad" }, images: [], prices: { price: { value: 18.99, currencyCode: "USD" }, salePrice: null, bulkPricing: [{ minimumQuantity: 10, maximumQuantity: 0 }] }, brand: { name: "Strathmore" }, reviewSummary: { summationOfRatings: 12, numberOfReviews: 3 }, customFields: [{ name: "Size", value: '11" x 14"' }, { name: "Weight", value: "184 lb" }] },
  { entityId: 407, name: "Stretched Canvas 36x48", path: "/products/stretched-canvas-36x48", category: "canvas-surfaces", plainTextDescription: "Large-format gallery-wrapped canvas, 36x48 inches. Heavy-duty staple-free back for clean presentation.", description: "<p>Large-format 36x48 gallery-wrapped canvas with staple-free back.</p>", defaultImage: { url: "/images/products/stretched-canvas-36x48.png", altText: "Large Stretched Canvas 36x48" }, images: [], prices: { price: { value: 59.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Fredrix" }, reviewSummary: { summationOfRatings: 15, numberOfReviews: 3 }, customFields: [{ name: "Size", value: '36" x 48"' }] },
  { entityId: 408, name: "Gessobord Panel Set (4-pack)", path: "/products/gessobord-panel-set", category: "canvas-surfaces", plainTextDescription: "Pre-primed hardboard panels in 4 sizes (8x10, 9x12, 11x14, 12x16). Smooth, archival surface.", description: "<p>Pre-primed hardboard panels in 4 sizes. Smooth, archival surface.</p>", defaultImage: { url: "/images/products/gessobord-panel-set.png", altText: "Gessobord Panel Set" }, images: [], prices: { price: { value: 44.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Ampersand" }, reviewSummary: { summationOfRatings: 16, numberOfReviews: 4 }, customFields: [{ name: "Sizes", value: '8x10, 9x12, 11x14, 12x16"' }] },

  // ===== STUDIO FURNITURE =====
  { entityId: 501, name: "Artist Taboret (4-Drawer)", path: "/products/artist-taboret-4-drawer", category: "studio-furniture", plainTextDescription: "Solid beechwood taboret with 4 drawers and a spacious top surface. Lockable casters for easy mobility.", description: "<p>Solid beechwood taboret with 4 drawers and lockable casters.</p>", defaultImage: { url: "/images/products/artist-taboret-4-drawer.png", altText: "Artist Taboret with 4 Drawers" }, images: [], prices: { price: { value: 349.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Best" }, reviewSummary: { summationOfRatings: 14, numberOfReviews: 3 }, customFields: [{ name: "Material", value: "Beechwood" }] },
  { entityId: 502, name: "Adjustable Drafting Table", path: "/products/adjustable-drafting-table", category: "studio-furniture", plainTextDescription: "Professional drafting table with adjustable angle and height. Tempered glass surface, steel frame.", description: "<p>Professional drafting table with adjustable angle and height. Tempered glass surface on a steel frame.</p>", defaultImage: { url: "/images/products/adjustable-drafting-table.png", altText: "Adjustable Drafting Table" }, images: [], prices: { price: { value: 449.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Studio Designs" }, reviewSummary: { summationOfRatings: 18, numberOfReviews: 4 }, customFields: [{ name: "Surface", value: "Tempered Glass" }] },
  { entityId: 503, name: "Paint Drying Rack (50 shelf)", path: "/products/paint-drying-rack", category: "studio-furniture", plainTextDescription: "50-shelf drying rack for wet paintings and prints. Spring-loaded shelves with non-stick coating.", description: "<p>50-shelf spring-loaded drying rack with non-stick coating.</p>", defaultImage: { url: "/images/products/paint-drying-rack.png", altText: "Paint Drying Rack" }, images: [], prices: { price: { value: 189.99, currencyCode: "USD" }, salePrice: { value: 159.99, currencyCode: "USD" }, bulkPricing: null }, brand: { name: "Art Expo" }, reviewSummary: { summationOfRatings: 10, numberOfReviews: 2 }, customFields: [{ name: "Shelves", value: "50" }] },
  { entityId: 504, name: "Rolling Supply Cart", path: "/products/rolling-supply-cart", category: "studio-furniture", plainTextDescription: "Three-tier rolling cart for art supplies. Heavy-gauge steel with powder coating, locking wheels.", description: "<p>Three-tier heavy-gauge steel rolling cart with locking wheels.</p>", defaultImage: { url: "/images/products/rolling-supply-cart.png", altText: "Rolling Art Supply Cart" }, images: [], prices: { price: { value: 79.99, currencyCode: "USD" }, salePrice: null, bulkPricing: [{ minimumQuantity: 5, maximumQuantity: 0 }] }, brand: { name: "Alvin" }, reviewSummary: { summationOfRatings: 8, numberOfReviews: 2 }, customFields: [{ name: "Tiers", value: "3" }] },
  { entityId: 505, name: "Wall-Mounted Art Storage", path: "/products/wall-mounted-art-storage", category: "studio-furniture", plainTextDescription: "Wall-mounted art storage system for canvases and boards. Adjustable dividers hold works up to 48 inches.", description: "<p>Wall-mounted storage system with adjustable dividers for canvases up to 48\".</p>", defaultImage: { url: "/images/products/wall-mounted-art-storage.png", altText: "Wall-Mounted Art Storage System" }, images: [], prices: { price: { value: 229.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Best" }, reviewSummary: { summationOfRatings: 12, numberOfReviews: 3 }, customFields: [{ name: "Max Size", value: '48"' }] },
  { entityId: 506, name: "Artist Stool (Adjustable)", path: "/products/artist-stool-adjustable", category: "studio-furniture", plainTextDescription: "Ergonomic artist stool with adjustable height and footrest. Padded seat with 360-degree swivel.", description: "<p>Ergonomic padded stool with adjustable height, footrest, and 360° swivel.</p>", defaultImage: { url: "/images/products/artist-stool-adjustable.png", altText: "Adjustable Artist Stool" }, images: [], prices: { price: { value: 149.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Studio Designs" }, reviewSummary: { summationOfRatings: 16, numberOfReviews: 4 }, customFields: [] },

  // ===== GIFT SETS =====
  { entityId: 601, name: "Beginner Oil Painting Set", path: "/products/beginner-oil-painting-set", category: "gift-sets", plainTextDescription: "Complete oil painting starter kit with tabletop easel, 12 paint tubes, brushes, palette, and canvas.", description: "<p>Everything a beginner needs: tabletop easel, 12 oil tubes, brushes, palette, and two canvases.</p>", defaultImage: { url: "/images/products/beginner-oil-painting-set.png", altText: "Beginner Oil Painting Set" }, images: [], prices: { price: { value: 129.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Winsor & Newton" }, reviewSummary: { summationOfRatings: 22, numberOfReviews: 5 }, customFields: [] },
  { entityId: 602, name: "Watercolor Travel Kit", path: "/products/watercolor-travel-kit", category: "gift-sets", plainTextDescription: "Portable watercolor set with 18 half-pans, travel brushes, mixing palette, and water brush pen.", description: "<p>Portable watercolor set with 18 half-pans, travel brushes, and water brush pen.</p>", defaultImage: { url: "/images/products/watercolor-travel-kit.png", altText: "Watercolor Travel Kit" }, images: [], prices: { price: { value: 79.99, currencyCode: "USD" }, salePrice: { value: 64.99, currencyCode: "USD" }, bulkPricing: null }, brand: { name: "Schmincke" }, reviewSummary: { summationOfRatings: 24, numberOfReviews: 6 }, customFields: [] },
  { entityId: 603, name: "Premium Sketching Collection", path: "/products/premium-sketching-collection", category: "gift-sets", plainTextDescription: "Luxury sketching set in a walnut box. Graphite pencils, charcoal, erasers, blending stumps, and sketchbook.", description: "<p>Luxury sketching set in a walnut box with graphite, charcoal, erasers, and blending stumps.</p>", defaultImage: { url: "/images/products/premium-sketching-collection.png", altText: "Premium Sketching Collection" }, images: [], prices: { price: { value: 94.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Caran d'Ache" }, reviewSummary: { summationOfRatings: 19, numberOfReviews: 4 }, customFields: [] },
  { entityId: 604, name: "Acrylic Pouring Starter Kit", path: "/products/acrylic-pouring-starter-kit", category: "gift-sets", plainTextDescription: "Everything needed for acrylic pouring: 8 fluid acrylics, pouring medium, cups, stir sticks, and canvases.", description: "<p>8 fluid acrylics, pouring medium, cups, stir sticks, and canvases for acrylic pouring.</p>", defaultImage: { url: "/images/products/acrylic-pouring-starter-kit.png", altText: "Acrylic Pouring Starter Kit" }, images: [], prices: { price: { value: 59.99, currencyCode: "USD" }, salePrice: null, bulkPricing: [{ minimumQuantity: 5, maximumQuantity: 0 }] }, brand: { name: "Liquitex" }, reviewSummary: { summationOfRatings: 14, numberOfReviews: 3 }, customFields: [] },
  { entityId: 605, name: "Artist's Studio Essentials Box", path: "/products/studio-essentials-box", category: "gift-sets", plainTextDescription: "Curated gift box with premium brushes, professional-grade paints, palette, and cleaning supplies.", description: "<p>Curated gift box with premium brushes, paints, palette, and cleaning supplies.</p>", defaultImage: { url: "/images/products/studio-essentials-box.png", altText: "Artist's Studio Essentials Box" }, images: [], prices: { price: { value: 199.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Various" }, reviewSummary: { summationOfRatings: 18, numberOfReviews: 4 }, customFields: [] },
  { entityId: 606, name: "Calligraphy Starter Set", path: "/products/calligraphy-starter-set", category: "gift-sets", plainTextDescription: "Complete calligraphy set with dip pen, 6 nibs, ink bottles, practice sheets, and instruction guide.", description: "<p>Dip pen, 6 nibs, ink bottles, practice sheets, and instruction guide.</p>", defaultImage: { url: "/images/products/calligraphy-starter-set.png", altText: "Calligraphy Starter Set" }, images: [], prices: { price: { value: 49.99, currencyCode: "USD" }, salePrice: null, bulkPricing: null }, brand: { name: "Speedball" }, reviewSummary: { summationOfRatings: 10, numberOfReviews: 2 }, customFields: [] },
];

// Fill in empty images arrays from defaultImage
for (const p of ALL_PRODUCTS) {
  if (p.images.length === 0) {
    p.images = singleGallery(p.defaultImage);
  }
}

// ---------------------------------------------------------------------------
// Lookups
// ---------------------------------------------------------------------------

/** Products grouped by category slug */
export function getProductsByCategory(categorySlug: string): SampleProduct[] {
  return ALL_PRODUCTS.filter((p) => p.category === categorySlug);
}

/** Find a single product by its URL path (e.g. "/products/chevalet-grand-h-frame") */
export function getProductByPath(path: string): SampleProduct | undefined {
  return ALL_PRODUCTS.find((p) => p.path === path);
}

/** Find a single product by its slug (the last segment of the path) */
export function getProductBySlug(slug: string): SampleProduct | undefined {
  return ALL_PRODUCTS.find((p) => p.path === `/products/${slug}`);
}

/** Get all products (for generating static paths, etc.) */
export function getAllProducts(): SampleProduct[] {
  return ALL_PRODUCTS;
}

/** Get up to N related products (same category, different product) */
export function getRelatedProducts(product: SampleProduct, count = 4): SampleProduct[] {
  return ALL_PRODUCTS
    .filter((p) => p.category === product.category && p.entityId !== product.entityId)
    .slice(0, count);
}
